version: '3.2'
services:
    perimeter-lb:
        build:
            context: ./zones/perimeter/perimeter-lb
        ports:
            - "80:80"
        networks:
            - perimeter

    static-lb:
        build:
            context: ./zones/static/static-lb
        networks:
            - perimeter
            - static
    static-web:
        build:
            context: ./zones/static/static-web
        networks:
            - static

    service-lb:
        build:
            context: ./zones/service/service-lb
        networks:
            - perimeter
            - service
    order-service:
        build:
            context: ./zones/service/order-service
        networks:
            - service
        depends_on:
          - mongo
    redis-master:
        image: redis:3
        networks:
            - service
    redis-slave:
        image: redis:3
        command: redis-server --slaveof redis-master 6379
        networks:
            - service
    redis-sentinel:
        build:
            context: ./zones/service/redis-sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=5000
        networks:
            - service
    mongo:
      image: mongo
      networks:
        - service

    elasticsearch:
        build:
            context: ./zones/service/elasticsearch
        networks:
            - service
        healthcheck:
            test: curl -f http://localhost:9200/_cluster/health
            interval: 10s
            timeout: 10s
            retries: 3
    logstash:
        build:
            context: ./zones/service/logstash
        networks:
            - service
#        depends_on:
#            - elasticsearch
        healthcheck:
            test: curl -f http://localhost:9600
            interval: 10s
            timeout: 10s
            retries: 3
    kibana:
        build:
            context: ./zones/service/kibana
        networks:
            - service
#        depends_on:
#            - elasticsearch
        healthcheck:
            test: curl -f http://localhost:5601/status
            interval: 10s
            timeout: 10s
            retries: 3
    grafana:
      build:
        context: ./zones/service/grafana
      networks:
        - service

#    ping-service:
#        build:
#            context: ./zones/service/ping-service
#        networks:
#            - service
#
#    ping-agent:
#        build:
#            context: ./zones/agent/ping-agent
#        environment:
#            - REQUESTS_PER_MINUTE=60
#        networks:
#            - perimeter
#            - agent
#        depends_on:
#            - order-service
#            - ping-service

networks:
    perimeter:
    static:
    service:
    agent:
